line_length:
  warning: 160
  error: 500
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

identifier_name:
  excluded: # excluded via string array
    - id
    - vc
    - x
    - y
    - on

disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - large_tuple

excluded:
  - .build
  - Pods
